com.mathworks.xml.XMLValidator.validate(...
'c:\documents and settings\dan\my documents\matlab\peoplesscripts\spectralhosa\hosa\info.xml',...
    'C:\Program Files\MATLAB\R2007b\sys\namespace\info\v1\info.xsd', true)