  Cloud_Effective_Radius_Liquid_Maximum                                1x1              190780680  struct              
  Cloud_Effective_Radius_Liquid_Mean                                   1x1              190780674  struct              
  Cloud_Effective_Radius_Liquid_Mean_Uncertainty                       1x1              190780698  struct              
  Cloud_Effective_Radius_Liquid_Minimum                                1x1              190780680  struct              
  Cloud_Effective_Radius_Liquid_Standard_Deviation                     1x1              190780702  struct              
  Cloud_Fraction_Liquid                                                1x1              190780642  struct              
  Cloud_Fraction_Liquid_Pixel_Counts                                   1x1              190780668  struct              
  Cloud_Optical_Thickness_Liquid_Joint_Histogram_vs_Effect_Radius      1x1              172118862  struct              
  Cloud_Optical_Thickness_Liquid_Maximum                               1x1              190780676  struct              
  Cloud_Optical_Thickness_Liquid_Mean                                  1x1              190780670  struct              
  Cloud_Optical_Thickness_Liquid_Mean_Uncertainty                      1x1              190780694  struct              
  Cloud_Optical_Thickness_Liquid_Minimum                               1x1              190780676  struct              
  Cloud_Optical_Thickness_Liquid_Standard_Deviation                    1x1              190780698  struct              
  Cloud_Top_Temperature_Day_Maximum                                    1x1              190780686  struct              
  Cloud_Top_Temperature_Day_Mean                                       1x1              190780680  struct              
  Cloud_Top_Temperature_Day_Minimum                                    1x1              190780686  struct              
  Cloud_Top_Temperature_Day_Standard_Deviation                         1x1              190780708  struct              
  H_timeseries                                                         1x1              377395552  struct              
  MLAT                                                                 1x180                 1440  double              
  MLON                                                                 1x360                 2880  double              
  Nd_timeseries                                                        1x1              377395552  struct              
  Scattering_Angle_Maximum                                             1x1              190780654  struct              
  Scattering_Angle_Mean                                                1x1              190780648  struct              
  Scattering_Angle_Minimum                                             1x1              190780654  struct              
  Scattering_Angle_Pixel_Counts                                        1x1              190780658  struct              
  Scattering_Angle_Standard_Deviation                                  1x1              190780676  struct              
  Sensor_Azimuth_Mean                                                  1x1              190780644  struct              
  Sensor_Zenith_Maximum                                                1x1              190780648  struct              
  Sensor_Zenith_Mean                                                   1x1              190780642  struct              
  Sensor_Zenith_Minimum                                                1x1              190780648  struct              
  Sensor_Zenith_Standard_Deviation                                     1x1              190780670  struct              
  Solar_Azimuth_Mean                                                   1x1              190780642  struct              
  Solar_Zenith_Maximum                                                 1x1              190780646  struct              
  Solar_Zenith_Mean                                                    1x1              190780640  struct              
  Solar_Zenith_Minimum                                                 1x1              190780646  struct              
  Solar_Zenith_Standard_Deviation                                      1x1              190780668  struct              
  W_timeseries 