direcDan(1).dir='les2.3tests\lesrad_tests\bauru\ccn6e7'
direcDan(2).dir='les2.3tests\lesrad_tests\bauru\ccn1.2e8'
direcDan(3).dir='les2.3tests\lesrad_tests\bauru\ccn1.8e8'
direcDan(4).dir='les2.3tests\lesrad_tests\bauru\ccn2.4e8'
direcDan(5).dir='les2.3tests\lesrad_tests\bauru\ccn3e8'
direcDan(6).dir='les2.3tests\lesrad_tests\bauru\ccn3.6e8'
