 dgs={'PGDEP','PGMLT', ...  %1-2
          'PRAUT',   'PGSHD',   'PRACW',   'PSMLT', ... %3-6
          'PIMLT',   'PSAUT',   'PSDEP',   'PIACR_G', ... %7-10
          'PSACI',   'PGACI',   'PGACW',   'PGACS', ... %11-14
          'PGACR',   'PSACR',   'PRACS',   'PSACW', ... %15-18
          'PGAUT',   'PGFR',    'PRACI_G', 'PGWET', ... %19-22
          'PGDRY',   'PGSUB',   'PSSUB',   'PREVP', ... %23-26
          'PISUB',   'DQI  ',   'PIHAL',   'PIPRM', ... %27-30
          'PIDEP',   'PIACW',   'PICNT',   'PIFRW', ... %31-34
          'PIACR_S', 'PRACI_S', 'PRACI',   'PIACR', ... %35-38
          'RIACR_S', 'RSACR',   'RIACR_G', 'RGFR', ...  %39-42
          'RGACS',   'RGACR',   'RSAUT',   'RIACI', ... %43-46
          'RSACS',   'RSBRK'  ...                       %47-48
          , 'RGmlt'		  ... %49
          , 'RSmlt'		   ...%50
          , 'RImlt'		  ...
          , 'RSaci'		  ...
          , 'RGaci'		  ... 
          , 'RGacw'		  ...  %??? - not used?
          , 'RRacs'		  ... %55
          , 'RGaut'		  ...
          , 'RGsub'		  ... 
          , 'RSsub'		  ...
          , 'RIcnt'		  ...
          , 'RIhal'		  ... %60
          , 'RIprm'		  ... 
          , 'RIfrw'		  ... 
          , 'RRaci_S'	  ... 
          , 'RRaci_G'	  ...
          , 'RSaut_I'	  ... %65
          , 'RSaut_S'	  ...
          , 'RGaut_S'	  ... 
          , 'RGaut_G'	  ...
          , 'RSacr_S'	  ...
          , 'RSacr_G' }   ;   %70